name: CI

on:
  push:
    branches: [ main ]
    tags: [ v* ] #trigger on tags start with v, eg v1.0.0
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      golang: ${{ steps.filter.outputs.golang }}
      js: ${{ steps.filter.outputs.js }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          filters: |
            golang:
              - "modelschemas/**"
              - "schemasv1/**"

  golint:
    runs-on: ubuntu-latest

    needs:
      - diff

    if: ${{ (github.event_name == 'pull_request' && needs.diff.outputs.golang == 'true') || github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2

      - name: Run gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: '-l -d'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44

concurrency:
  group: yatai${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

